In [2]:
#Pre-requisites
import numpy as np
import pandas as pd

1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series<br>
	Values<br>
	Index<br>
	Data type<br>
	Mean<br>
	Maximum<br>
	Minimum<br>

In [3]:
marks_1 = pd.Series([78,85,92,67,88])
print("Complete Series:")
print(marks_1)
print("Values:", marks_1.values)
print("Index:",marks_1.index)
print("Data type:", marks_1.dtype)
print("Mean:", marks_1.mean())
print("Maximum:", marks_1.max())
print("Minimum:", marks_1.min())

Complete Series:
0    78
1    85
2    92
3    67
4    88
dtype: int64
Values: [78 85 92 67 88]
Index: RangeIndex(start=0, stop=5, step=1)
Data type: int64
Mean: 82.0
Maximum: 92
Minimum: 67

2. Create a Series containing:
 
   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
 Display the marks of Meena.

In [4]:
studmarks=pd.Series([85, 78, 92, 74, 88], index=['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'])
print(studmarks['Meena'])

92

3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types

In [5]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"],
    "Marks": [85, 78, 92, 74, 88]
}
df=pd.DataFrame(data)
print("Complete Dataframe:\n", df)
print("\nFirst Three rows:\n",df[:3])
print("\nLast 2 rows:\n", df[-2:])
print("\nShape:", df.shape)
print("\nColumn names:", df.columns)
print("\nDatatypes:\n", df.dtypes)

Complete Dataframe:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First Three rows:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:
     Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape: (5, 4)

Column names: Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')

Datatypes:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object

4. Using the previous DataFrame, display:

	info()<br>
	describe()<br>
	Number of rows<br>
	Number of columns<br>

In [6]:
print("info():\n", df.info())
print("\ndescribe():\n", df.describe())
print("\nNumber of rows:", df.shape[0])
print("\nNumber of columns:", df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes
info():
 None

describe():
              Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Number of rows: 5

Number of columns: 4

5. Using df, display:

	Name column<br>
	Marks column<br>
	Name and Marks together<br>

In [7]:
print("Name column:\n", df.Name)
print("Marks column:\n", df.Marks)
print("Name and Marks columns together:\n", df[['Name','Marks']])

Name column:
 0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: object
Marks column:
 0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64
Name and Marks columns together:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

6. Display:

	+ First row using iloc
	+ Third row using iloc
	+ Rows 1 to 3
	+ Name and Marks columns using loc

In [8]:
print("First row using iloc:\n", df.iloc[0])
print("Third row using iloc:\n", df.iloc[2])
print("First three rows using iloc\n", df.iloc[:3])
print("Name and Marks columns using loc:\n", df.loc[:,['Name', 'Marks']])

First row using iloc:
 Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object
Third row using iloc:
 Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object
First three rows using iloc
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
Name and Marks columns using loc:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

7. Find:

	+ Students scoring above 80.
	+ Students scoring between 75 and 90.
	+ Students belonging to CSE.
	+ CSE students scoring above 80.

In [9]:
print("Students scoring above 80:\n", df.loc[df['Marks']>80])
print("Students scoring between 75 and 90:\n", df.loc[(df['Marks']>75) & (df['Marks']<90)])
print("Students belonging to CSE:\n", df.loc[df['Department'] == 'CSE'])
print("CSE students scoring above 80:\n", df.loc[(df['Department'] == 'CSE') & (df['Marks']>80)])

Students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88
Students scoring between 75 and 90:
    Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88
Students belonging to CSE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
CSE students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

8. Display students belonging to either CSE or ECE.

In [10]:
print("Display students belonging to either CSE or ECE:\n",
df.loc[(df["Department"] == "CSE") | (df["Department"] == 'ECE')])

Display students belonging to either CSE or ECE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [11]:
df["Result"] = df['Marks'].apply(lambda x : "Pass" if x > 75 else 'Fail')
df

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

In [12]:
df['Grade'] = np.select([
    df['Marks'] >= 90,
    df['Marks'] >= 80,
    df['Marks'] >= 70
],
[
    'A','B','C'
], default='D')
df

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

11. Sort students:

	+ By marks in ascending order.
	+ By marks in descending order.
	+ By Department and then Marks.

In [13]:
df.sort_values('Department')

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:<br>

+ Missing values
+ Number of missing values in each column
+ Rows containing missing values

In [14]:
from sklearn.impute import SimpleImputer
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}
students = pd.DataFrame(data)
print(students.info)
print(students.isnull())
print(students.isnull().sum())
print(students[students.isnull().any(axis=1)])

<bound method DataFrame.info of     Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0>
    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False
Name     0
Age      1
Marks    1
dtype: int64
    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

13. Replace:

	+ Missing Age with average Age
	+ Missing Marks with average Marks

In [15]:
x = students.iloc[:, 1:3].values
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer = imputer.fit(x)
x = imputer.transform(x)
x

array([[22.  , 85.  ],
       [23.  , 84.75],
       [22.75, 92.  ],
       [24.  , 74.  ],
       [22.  , 88.  ]])


14. Remove rows containing missing values.

In [16]:
students[students.notnull().all(axis=1)]

    Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

- Find duplicates:
- Display duplicate rows:
- Remove duplicates:

In [17]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

print(df2[df2.duplicated()])
df2 = df2.drop_duplicates()
print(df2)

   Name  Marks
3  Asha     85
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

- Mean
- Median
- Maximum
- Minimum
- Standard deviation
- Sum

In [18]:
marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})
print("mean:",marks["Marks"].mean())
print("Median:", marks["Marks"].median())
print("Max:", marks["Marks"].max())
print("Min:", marks["Marks"].min())
print("Std:", marks["Marks"].std())
print("Sum:", marks["Marks"].sum())

mean: 82.0
Median: 85.0
Max: 92
Min: 67
Std: 9.82344135219425
Sum: 410

17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
- Average marks by department
- Maximum marks by department
- Number of students in each department

For each department, calculate:
- Mean
- Minimum
- Maximum
- Count

In [19]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)

df.groupby("Department")["Marks"].agg(["mean", "min", "max", "count"])

                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.

In [36]:
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})
pd.merge(students, marks)

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

- Display the first five records.
- Find the dimensions of the dataset.
- Find the average final mark.
- Find the highest-scoring student.
- Find the lowest-scoring student.
- Display students scoring above 80.
- Find average marks by department.
- Find students having attendance above 80%.
- Sort students by FinalMarks.
- Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
- Add a performance category:
	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement
- Find the department having the highest average FinalMarks.

In [ ]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)

print("Display the first five records\n", df[:5])
print("Dimensions of the dataset.\n", df.shape)
print("Average final mark: ", df["FinalMarks"].mean())
print("Highest-scoring student:\n", df[(df["FinalMarks"]) == df["FinalMarks"].max()])
print("Lowest-scoring student:\n", df[(df["FinalMarks"]) == df["FinalMarks"].min()])
print("Display students scoring above 80:\n", df[(df["FinalMarks"]) > 80])
print("Average marks by department:n", df.groupby('Department')['FinalMarks'].agg("mean"))

Display the first five records
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
Dimensions of the dataset.
 (8, 5)
Average final mark:  81.625
Highest-scoring student:
     Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
Lowest-scoring student:
     Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
Display students scoring above 80:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
Average marks by department:n Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64
Students having attendance above 80%:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
Sort students by FinalMarks:
     Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96

In [60]:
print("Students having attendance above 80%:\n", df[(df["Attendance"]) > 80])
print("Sort students by FinalMarks:\n", df.sort_values("FinalMarks"))
print("Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail:")
df["Result"] = np.select(
    [
        df["FinalMarks"] > 70,
    ],
    [
        "Pass"
    ],
    default="Fail"
)
df

Students having attendance above 80%:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
Sort students by FinalMarks:
     Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96
Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail:

    Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

In [62]:
print("Add a performance category:\n≥90 → Excellent\n≥80 → Very Good\n≥70 → Good\n<70 → Needs Improvement\n")
df["Performance"] = np.select(
    [
        df["FinalMarks"] >= 90,
        df["FinalMarks"] >= 80,
        df["FinalMarks"] >= 70
    ],
    [
        "Excellent",
        "Very Good",
        "Good"
    ],
    default="Needs Improvement"
)
df

Add a performance category:
≥90 → Excellent
≥80 → Very Good
≥70 → Good
<70 → Needs Improvement

,Name,Department,Attendance,Internal,FinalMarks,Result,Performance
0,Asha,CSE,92,85,88,Pass,Very Good
1,Ravi,ECE,75,72,74,Pass,Good
2,Meena,CSE,96,94,96,Pass,Excellent
3,Kiran,ME,68,65,62,Fail,Needs Improvement
4,Arun,ECE,82,80,83,Pass,Very Good
5,Divya,CSE,88,86,89,Pass,Very Good
6,John,ME,72,70,68,Fail,Needs Improvement
7,Priya,ECE,95,91,93,Pass,Excellent

In [68]:
print("Highest average marks by department:", df.groupby('Department')['FinalMarks'].agg("mean").max())

Highest average marks by department: 91.0

20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

- Average salary.
- Maximum and minimum salary.
- Employee receiving the highest salary.
- Employees earning above ₹60,000.
- Average salary for each department.
- Average experience by department.
- Number of employees in each department.
- Sort employees by salary.
- Find IT employees with more than 3 years of experience.
- Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low

In [69]:
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

In [71]:
print("Average Salary:", employees["Salary"].mean())
print("Maximum Salary:", employees["Salary"].max())
print("Minimum Salary:", employees["Salary"].min())
print("\nHighest Paid Employee:\n", employees.loc[employees["Salary"].idxmax()])

Average Salary: 62875.0
Maximum Salary: 85000
Minimum Salary: 45000

Highest Paid Employee:
 Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

In [73]:
print("Employees earning above ₹60,000:\n", employees[employees["Salary"] > 60000])
print("\nAverage Salary by Department:\n", employees.groupby("Department")["Salary"].mean())
print("\nAverage Experience by Department:\n", employees.groupby("Department")["Experience"].mean())
print("\nNumber of Employees in Each Department:\n", employees["Department"].value_counts())

Employees earning above ₹60,000:
   Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

Average Salary by Department:
 Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

Average Experience by Department:
 Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

Number of Employees in Each Department:
 IT         3
Finance    3
HR         2
Name: Department, dtype: int64

In [74]:
print("\nEmployees Sorted by Salary:\n", employees.sort_values("Salary"))
print("\nIT Employees with More Than 3 Years Experience:\n", employees[(employees["Department"] == "IT") & (employees["Experience"] > 3)])

Employees Sorted by Salary:
   Employee Department  Experience  Salary
1      E02         HR           3   45000
6      E07         IT           2   48000
4      E05         HR           6   55000
0      E01         IT           5   60000
3      E04    Finance           4   65000
7      E08    Finance           5   70000
2      E03         IT           7   75000
5      E06    Finance           8   85000

IT Employees with More Than 3 Years Experience:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

In [75]:
"""Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low"""

employees["SalaryLevel"] = np.select(
    [
        employees["Salary"] >= 75000,
        employees["Salary"] >= 50000
    ],
    [
        "High",
        "Medium"
    ],
    default="Low"
)
employees

  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium